# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RSACrossPlatform' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RSACrossPlatform

  pod "MIHCrypto", "~> 0.4.0"

  target 'RSACrossPlatformTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RSACrossPlatformUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
